

# Simple Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: scylla-non-prod
  namespace: scylla-cluster
spec:
  version: 5.2.7
  agentVersion: 3.1.2
  developerMode: true
  backups:
  - name: "Daily Backup"
    rateLimit: ["50"]
    location: ["gcs:scylla-bucket-non-prod"]
    interval: "1d"
    retention: 7
  datacenter:
    name: europe-west3
    racks:
      - name: europe-west-3b
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config-secret"
        members: 4
        storage:
          capacity: 75Gi
          storageClassName: standard-rwo
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 900m
            memory: 2Gi
        placement:
          tolerations:
          - effect: NoSchedule
            key: role
            operator: Equal
            value: scylla-non-prod
        agentVolumeMounts:
          - name: scylla-manager-agent-gcs-service-account-volume
            mountPath: /mnt/scylla-manager-agent/gcp-sa.json
            subPath: gcp-sa.json
        volumes:
          - name: scylla-manager-agent-gcs-service-account-volume
            secret:
              secretName: gcs-service-account
